// export const ProductData = [
//   {
//     type: "Produk",
//     category: "Seni Rupa",
//     name: "Lukisan Abstrak Khas Jawa Tengah",
//     price: 1500000,
//     rating: 4.6,
//     region: "Semarang",
//     sold: 52,
//     images: [
//       "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715042022-Lukisan-Balinese-Procession-karya-Lee-Man-Fong-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//       "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715012022-Lukisan-Badai-Pasti-Berlalu-karya-Affandi-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//       "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0714572022-Lukisan-Berburu-Rusa-karya-Raden-Saleh-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia-(1).jpg",
//     ],
//   },
//   {
//     type: "Jasa",
//     category: "Seni Tari",
//     name: "Tari Bali",
//     price: 1500000,
//     rating: 4.9,
//     region: "Bali",
//     sold: 10,
//     images: [
//       "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715042022-Lukisan-Balinese-Procession-karya-Lee-Man-Fong-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//       "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715012022-Lukisan-Badai-Pasti-Berlalu-karya-Affandi-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//       "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0714572022-Lukisan-Berburu-Rusa-karya-Raden-Saleh-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia-(1).jpg",
//     ],
//   },
//   {
//     type: "Jasa",
//     category: "Seni Tari",
//     name: "Tari Bali",
//     price: 1500000,
//     rating: 4.9,
//     region: "Bali",
//     sold: 10,
//     images: [
//       "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715042022-Lukisan-Balinese-Procession-karya-Lee-Man-Fong-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//       "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715012022-Lukisan-Badai-Pasti-Berlalu-karya-Affandi-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//       "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0714572022-Lukisan-Berburu-Rusa-karya-Raden-Saleh-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia-(1).jpg",
//     ],
//   },
//   // {
//   //   type: "product",
//   //   category: "Seni Rupa",
//   //   name: "Lukisan Abstrak Khas Jawa Tengah",
//   //   price: 1500000,
//   //   rating: 4.6,
//   //   region: "Semarang",
//   //   sold: 52,
//   //   images: [
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715042022-Lukisan-Balinese-Procession-karya-Lee-Man-Fong-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715012022-Lukisan-Badai-Pasti-Berlalu-karya-Affandi-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0714572022-Lukisan-Berburu-Rusa-karya-Raden-Saleh-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia-(1).jpg",
//   //   ],
//   // },
//   // {
//   //   type: "service",
//   //   category: "Seni Tari",
//   //   name: "Tari Bali",
//   //   price: 1500000,
//   //   rating: 4.9,
//   //   region: "Bali",
//   //   sold: 10,
//   //   images: [
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715042022-Lukisan-Balinese-Procession-karya-Lee-Man-Fong-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715012022-Lukisan-Badai-Pasti-Berlalu-karya-Affandi-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0714572022-Lukisan-Berburu-Rusa-karya-Raden-Saleh-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia-(1).jpg",
//   //   ],
//   // },
//   // {
//   //   type: "product",
//   //   category: "Seni Rupa",
//   //   name: "Lukisan Abstrak Khas Jawa Tengah",
//   //   price: 1500000,
//   //   rating: 4.6,
//   //   region: "Semarang",
//   //   sold: 52,
//   //   images: [
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715042022-Lukisan-Balinese-Procession-karya-Lee-Man-Fong-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715012022-Lukisan-Badai-Pasti-Berlalu-karya-Affandi-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0714572022-Lukisan-Berburu-Rusa-karya-Raden-Saleh-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia-(1).jpg",
//   //   ],
//   // },
//   // {
//   //   type: "service",
//   //   category: "Seni Tari",
//   //   name: "Tari Bali",
//   //   price: 1500000,
//   //   rating: 4.9,
//   //   region: "Bali",
//   //   sold: 10,
//   //   images: [
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715042022-Lukisan-Balinese-Procession-karya-Lee-Man-Fong-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715012022-Lukisan-Badai-Pasti-Berlalu-karya-Affandi-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0714572022-Lukisan-Berburu-Rusa-karya-Raden-Saleh-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia-(1).jpg",
//   //   ],
//   // },
//   // {
//   //   type: "product",
//   //   category: "Seni Rupa",
//   //   name: "Lukisan Abstrak Khas Jawa Tengah",
//   //   price: 1500000,
//   //   rating: 4.6,
//   //   region: "Semarang",
//   //   sold: 52,
//   //   images: [
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715042022-Lukisan-Balinese-Procession-karya-Lee-Man-Fong-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715012022-Lukisan-Badai-Pasti-Berlalu-karya-Affandi-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0714572022-Lukisan-Berburu-Rusa-karya-Raden-Saleh-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia-(1).jpg",
//   //   ],
//   // },
//   // {
//   //   type: "service",
//   //   category: "Seni Tari",
//   //   name: "Tari Bali",
//   //   price: 1500000,
//   //   rating: 4.9,
//   //   region: "Bali",
//   //   sold: 10,
//   //   images: [
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715042022-Lukisan-Balinese-Procession-karya-Lee-Man-Fong-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0715012022-Lukisan-Badai-Pasti-Berlalu-karya-Affandi-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia.jpg",
//   //     "https://cdngnfi2.sgp1.cdn.digitaloceanspaces.com/gnfi/uploads/images/2022/11/0714572022-Lukisan-Berburu-Rusa-karya-Raden-Saleh-menjadi-salah-satu-lukisan-terkenal-dunia-asal-Indonesia-Good-News-From-Indonesia-(1).jpg",
//   //   ],
//   // },
// ];


export const ProductData = [
  {
    "id": 10,
    "name": "Gamelan Jawa",
    "price": 2020202,
    "desc": "<p>{</p><p>    \"status\": \"error\",</p><p>    \"code\": 400,</p><p>    \"message\": \"Validation failed\",</p><p>    \"errors\": {</p><p>        \"thumbnail\": [</p><p>            \"The thumbnail field must be a file of type: jpeg, png, jpg, gif.\"</p><p>        ]</p><p>    }</p><p>}</p><p>{</p><p>    \"status\": \"error\",</p><p>    \"code\": 400,</p><p>    \"message\": \"Validation failed\",</p><p>    \"errors\": {</p><p>        \"thumbnail\": [</p><p>            \"The thumbnail field must be a file of type: jpeg, png, jpg, gif.\"</p><p>        ]</p><p>    }</p><p>}{</p><p>    \"status\": \"error\",</p><p>    \"code\": 400,</p><p>    \"message\": \"Validation failed\",</p><p>    \"errors\": {</p><p>        \"thumbnail\": [</p><p>            \"The thumbnail field must be a file of type: jpeg, png, jpg, gif.\"</p><p>        ]</p><p>    }</p><p>}{</p><p>    \"status\": \"error\",</p><p>    \"code\": 400,</p><p>    \"message\": \"Validation failed\",</p><p>    \"errors\": {</p><p>        \"thumbnail\": [</p><p>            \"The thumbnail field must be a file of type: jpeg, png, jpg, gif.\"</p><p>        ]</p><p>    }</p><p>}{</p><p>    \"status\": \"error\",</p><p>    \"code\": 400,</p><p>    \"message\": \"Validation failed\",</p><p>    \"errors\": {</p><p>        \"thumbnail\": [</p><p>            \"The thumbnail field must be a file of type: jpeg, png, jpg, gif.\"</p><p>        ]</p><p>    }</p><p>}</p>",
    "stock": 222,
    "status": 0,
    "thumbnail": "http://127.0.0.1:8000/storage/thumbnails/Q70m6bk88aqz7v0hSOm9fReDjtKsPkgw4aahUBrW.jpg",
    "category_id": 1,
    "shop_id": 1,
    "sold": 0,
    "created_at": "2024-09-28T16:15:32.000000Z",
    "updated_at": "2024-09-28T16:15:32.000000Z",
    "average_rating": 0,
    "rating_count": 0,
    "category": {
      "id": 1,
      "name": "Seni Musik",
      "created_at": null,
      "updated_at": null
    },
    "shop": {
      "id": 1,
      "name": "Sanggar Kesenian",
      "desc": "Jualaan Tari Daerah",
      "lat": null,
      "lng": null,
      "address": "Jl Jl",
      "profile_picture": null,
      "status": 1,
      "balance": 0,
      "city_id": 19,
      "province_id": 3,
      "user_id": 3,
      "created_at": "2024-09-28T13:23:17.000000Z",
      "updated_at": "2024-09-28T13:23:25.000000Z",
      "region": "Kabupaten Pandeglang, Banten",
      "city": {
        "id": 19,
        "province_id": 3,
        "type": "Kabupaten",
        "name": "Kabupaten Pandeglang",
        "postal_code": "42212",
        "created_at": "2024-09-28T11:28:26.000000Z",
        "updated_at": "2024-09-28T11:28:26.000000Z",
        "province": {
          "id": 3,
          "name": "Banten",
          "created_at": "2024-09-28T11:28:23.000000Z",
          "updated_at": "2024-09-28T11:28:23.000000Z"
        }
      }
    }
  },
  {
    "id": 11,
    "name": "Gitar buagos",
    "price": 4000000,
    "desc": "Uantik POL REK",
    "stock": 200,
    "status": 0,
    "thumbnail": "http://127.0.0.1:8000/storage/thumbnails/Rko05GrmpNzJAWXf4v12TmiaDS8B3tQt8K5n4WHc.png",
    "category_id": 1,
    "shop_id": 1,
    "sold": 0,
    "created_at": "2024-09-28T16:18:27.000000Z",
    "updated_at": "2024-09-28T16:18:27.000000Z",
    "average_rating": 0,
    "rating_count": 0,
    "category": {
      "id": 1,
      "name": "Seni Musik",
      "created_at": null,
      "updated_at": null
    },
    "shop": {
      "id": 1,
      "name": "Sanggar Kesenian",
      "desc": "Jualaan Tari Daerah",
      "lat": null,
      "lng": null,
      "address": "Jl Jl",
      "profile_picture": null,
      "status": 1,
      "balance": 0,
      "city_id": 19,
      "province_id": 3,
      "user_id": 3,
      "created_at": "2024-09-28T13:23:17.000000Z",
      "updated_at": "2024-09-28T13:23:25.000000Z",
      "region": "Kabupaten Pandeglang, Banten",
      "city": {
        "id": 19,
        "province_id": 3,
        "type": "Kabupaten",
        "name": "Kabupaten Pandeglang",
        "postal_code": "42212",
        "created_at": "2024-09-28T11:28:26.000000Z",
        "updated_at": "2024-09-28T11:28:26.000000Z",
        "province": {
          "id": 3,
          "name": "Banten",
          "created_at": "2024-09-28T11:28:23.000000Z",
          "updated_at": "2024-09-28T11:28:23.000000Z"
        }
      }
    }
  },
  {
    "id": 6,
    "name": "Batik Jawa",
    "price": 300000,
    "desc": "<p>Selamat datang di koleksi <strong>Batik Jawa Tradisional</strong>, di mana keindahan seni dan budaya berpadu dalam setiap helai kain. Batik ini merupakan warisan budaya Indonesia yang kaya, diolah dengan teknik dan motif yang telah diwariskan secara turun-temurun, menciptakan karya yang tidak hanya indah, tetapi juga sarat makna.</p>",
    "stock": 2,
    "status": 0,
    "thumbnail": "http://127.0.0.1:8000/storage/thumbnails/M3R2XZVp4qOKbq3BIo1QlowH8ZiBclQbgqiGWNIw.jpg",
    "category_id": 2,
    "shop_id": 1,
    "sold": 0,
    "created_at": "2024-09-28T13:50:47.000000Z",
    "updated_at": "2024-09-28T13:50:47.000000Z",
    "average_rating": 0,
    "rating_count": 0,
    "category": {
      "id": 2,
      "name": "Seni Kriya",
      "created_at": null,
      "updated_at": null
    },
    "shop": {
      "id": 1,
      "name": "Sanggar Kesenian",
      "desc": "Jualaan Tari Daerah",
      "lat": null,
      "lng": null,
      "address": "Jl Jl",
      "profile_picture": null,
      "status": 1,
      "balance": 0,
      "city_id": 19,
      "province_id": 3,
      "user_id": 3,
      "created_at": "2024-09-28T13:23:17.000000Z",
      "updated_at": "2024-09-28T13:23:25.000000Z",
      "region": "Kabupaten Pandeglang, Banten",
      "city": {
        "id": 19,
        "province_id": 3,
        "type": "Kabupaten",
        "name": "Kabupaten Pandeglang",
        "postal_code": "42212",
        "created_at": "2024-09-28T11:28:26.000000Z",
        "updated_at": "2024-09-28T11:28:26.000000Z",
        "province": {
          "id": 3,
          "name": "Banten",
          "created_at": "2024-09-28T11:28:23.000000Z",
          "updated_at": "2024-09-28T11:28:23.000000Z"
        }
      }
    }
  },
  {
    "id": 4,
    "name": "Lukisan Jawa",
    "price": 150000,
    "desc": "<p>Nikmati keindahan seni lukis Jawa yang kaya akan makna dan simbol. Setiap lukisan menggambarkan kekayaan budaya, mitologi, dan kehidupan sehari-hari masyarakat Jawa. Dengan teknik pelukisan yang halus dan penggunaan warna-warna alam yang cerah, setiap karya menciptakan nuansa yang mendalam dan memikat.</p>",
    "stock": 1,
    "status": 0,
    "thumbnail": "http://127.0.0.1:8000/storage/thumbnails/ESgPzNv7hFUh0cwIilp23sycdMjqYeg4udLGiJGx.jpg",
    "category_id": 2,
    "shop_id": 1,
    "sold": 0,
    "created_at": "2024-09-28T13:44:31.000000Z",
    "updated_at": "2024-09-28T13:44:31.000000Z",
    "average_rating": 0,
    "rating_count": 0,
    "category": {
      "id": 2,
      "name": "Seni Kriya",
      "created_at": null,
      "updated_at": null
    },
    "shop": {
      "id": 1,
      "name": "Sanggar Kesenian",
      "desc": "Jualaan Tari Daerah",
      "lat": null,
      "lng": null,
      "address": "Jl Jl",
      "profile_picture": null,
      "status": 1,
      "balance": 0,
      "city_id": 19,
      "province_id": 3,
      "user_id": 3,
      "created_at": "2024-09-28T13:23:17.000000Z",
      "updated_at": "2024-09-28T13:23:25.000000Z",
      "region": "Kabupaten Pandeglang, Banten",
      "city": {
        "id": 19,
        "province_id": 3,
        "type": "Kabupaten",
        "name": "Kabupaten Pandeglang",
        "postal_code": "42212",
        "created_at": "2024-09-28T11:28:26.000000Z",
        "updated_at": "2024-09-28T11:28:26.000000Z",
        "province": {
          "id": 3,
          "name": "Banten",
          "created_at": "2024-09-28T11:28:23.000000Z",
          "updated_at": "2024-09-28T11:28:23.000000Z"
        }
      }
    }
  },
  {
    "id": 5,
    "name": "Ukiran Kayu Jepara",
    "price": 200000,
    "desc": "<p>Masuki dunia keindahan dan kerajinan tangan dengan <strong>Ukiran Kayu Jepara</strong>, produk seni yang memancarkan keanggunan dan keahlian para pengrajin lokal. Setiap ukiran adalah hasil dari tradisi yang telah diwariskan turun-temurun, mencerminkan budaya dan estetika yang khas dari daerah Jepara, Jawa Tengah.</p>",
    "stock": 1,
    "status": 0,
    "thumbnail": "http://127.0.0.1:8000/storage/thumbnails/07L5vkBV0Y4Zh94Q4IiDE2JoPlo4AHZyunI0zKyH.png",
    "category_id": 2,
    "shop_id": 1,
    "sold": 0,
    "created_at": "2024-09-28T13:45:31.000000Z",
    "updated_at": "2024-09-28T13:45:31.000000Z",
    "average_rating": 0,
    "rating_count": 0,
    "category": {
      "id": 2,
      "name": "Seni Kriya",
      "created_at": null,
      "updated_at": null
    },
    "shop": {
      "id": 1,
      "name": "Sanggar Kesenian",
      "desc": "Jualaan Tari Daerah",
      "lat": null,
      "lng": null,
      "address": "Jl Jl",
      "profile_picture": null,
      "status": 1,
      "balance": 0,
      "city_id": 19,
      "province_id": 3,
      "user_id": 3,
      "created_at": "2024-09-28T13:23:17.000000Z",
      "updated_at": "2024-09-28T13:23:25.000000Z",
      "region": "Kabupaten Pandeglang, Banten",
      "city": {
        "id": 19,
        "province_id": 3,
        "type": "Kabupaten",
        "name": "Kabupaten Pandeglang",
        "postal_code": "42212",
        "created_at": "2024-09-28T11:28:26.000000Z",
        "updated_at": "2024-09-28T11:28:26.000000Z",
        "province": {
          "id": 3,
          "name": "Banten",
          "created_at": "2024-09-28T11:28:23.000000Z",
          "updated_at": "2024-09-28T11:28:23.000000Z"
        }
      }
    }
  }
]
